site_name: Brand Guide
site_url: https://fiware-brand-guide.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/brand-guide
site_description: FIWARE Brand Guideline
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code
extra_css:
  - https://www.fiware.org/style/fiware_readthedocs.css
  - https://www.fiware.org/custom/brand-guide/css/fiware_readthedocs_brand-guide.css
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js
  - https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js
  - https://www.fiware.org/custom/brand-guide/js/app_brand-guide.js
nav:
  - Home: 'index.md'
  - 'Logo': 
    - 'FIWARE': 'logo-fiware.md' 
    - 'FIWARE Foundation': 'logo-foundation.md'
    - 'FIWARE Ecosystem': 'logo-ecosystem.md'
  - 'Badges': 
    - 'FIWARE Catalogue': 'badge-catalogue.md'
    - 'FIWARE Domains': 'badge-domains.md'
    - 'FIWARE Marketplace': 'badge-marketplace.md' 
  - 'Resources': 
    - 'Fonts': 'fonts.md' 
    - 'Colors': 'colors.md'
