site_name: Brand Guide
site_url: https://fiware-brand-guide.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/brand-guide
site_description: FIWARE Brand Guideline
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code
extra_css:
  - https://www.fiware.org/style/fiware_readthedocs.css
  - https://www.fiware.org/style/fiware_readthedocs_brand-guide.css
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
extra_javascript:
  - https://gist.github.com/tommedema/c99079f90e49f5e545feb2a50d594f6e.js
nav:
  - Home: 'index.md'
  - 'Logo': 
    - 'FIWARE': 'logo-fiware.md' 
    - 'FIWARE Foundation': 'logo-foundation.md'
    - 'FIWARE Ecosystem': 'logo-ecosystem.md'
    - 'FIWARE Badges': 'logo-badges.md'
  - 'Resources': 
    - 'Fonts': 'fonts.md' 
    - 'Colors': 'colors.md'
