site_name: Brand Guide
site_url: https://fiware-brand-guide.readthedocs.org
repo_url: https://github.com/FIWARE-Ops/brand-guide
site_description: FIWARE Brand Guideline
docs_dir: docs
site_dir: html
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - fenced_code
extra_css: ["https://www.fiware.org/style/fiware_readthedocs.css"]
nav:
  - Home: 'index.md'
  - 'Logo': 
    - 'FIWARE': 'logo-fiware.md' 
    - 'FIWARE Foundation': 'logo-foundation.md'
    - 'FIWARE Domains': 'logo-domains.md'
    - 'FIWARE Components': 'logo-components.md'
    - 'FIWARE Ecosystem': 'logo-ecosystem.md'
  - 'Logo Usage': 
    - 'Clear Space': 'clear-space.md' 
    - 'Sizes': 'sizes.md'
    - 'On Backgrounds': 'on-backgrounds.md'
    - 'Dontâ€™s': 'donts.md'
  - 'Settings': 
    - 'Fonts': 'fonts.md' 
    - 'Colors': 'colors.md'
